#!/bin/sh /etc/rc.common

START=95
STOP=05
USE_PROCD=1

start_service() {
    config_load simpleadmin
    config_get_bool enabled simpleadmin enabled 1
    [ "$enabled" -eq 1 ] || return 0
    config_get listen_addr simpleadmin listen_addr '192.168.1.1'
    config_get port simpleadmin port '8080'
    config_get static_dir simpleadmin static_dir '/usr/share/simpleadmin/www'
    config_get auth_file simpleadmin auth_file '/etc/simpleadmin/auth'
    procd_open_instance
    procd_set_param command /usr/bin/simpleadmin-httpd --no-tls=true --http "${listen_addr}:${port}" --static "$static_dir" --auth-file "$auth_file"
    procd_set_param respawn 3600 5 5
    procd_set_param file /etc/config/simpleadmin
    procd_close_instance
}
